services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production

  frontend:
    build:
      context: ./frontend/itd
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
